name: Actualizar README

on:
  schedule:
    - cron: "0 0 * * *" # Todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Actualizar actividad reciente
        uses: jamesgeorge007/github-activity-readme@v0.3.6
        with:
          GH_USERNAME: crisporcal
          MAX_LINES: 5
