name: Actualizar actividad reciente en README

on:
  schedule:
    - cron: "0 */6 * * *"  # cada 6 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Actualizar actividad en README
        uses: Readme-Workflows/recent-activity@v1.0.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          username: crisporcal
          commit_message: "⚡ Actualizar actividad reciente"
          max_days: 30
