name: Update README with GitHub Activity

on:
  schedule:
    - cron: "0 0 * * *" # cada 24 horas (a medianoche UTC)
  workflow_dispatch: # para correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@v0.3.6
        with:
          COMMIT_MSG: "⚡ Update README with the recent activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
